# Railway部署配置文件 - DSE AI Teacher API Backend
# 这个配置适用于FastAPI Python应用的Railway部署

[variables]
# 设置Python版本
PYTHON_VERSION = "3.11"
# 禁用Python字节码缓存，减少容器大小
PYTHONDONTWRITEBYTECODE = "1"
# 确保输出不缓冲，便于日志查看
PYTHONUNBUFFERED = "1"
# 设置UTF-8编码
PYTHONIOENCODING = "utf-8"
# 让Python能找到自定义安装位置的包
PYTHONPATH = "/app/.python_packages/lib/python3.11/site-packages"

[phases.setup]
# 安装系统依赖
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
# 安装Python依赖到自定义目录，避免修改系统Python（PEP 668）
cmds = [
    "pip install --no-cache-dir --target=/app/.python_packages -r backend/requirements.txt"
]

[phases.build]
# 构建阶段 - 确保数据目录和日志目录存在
cmds = [
    "mkdir -p backend/logs",
    "mkdir -p data"
]

[start]
# 启动命令 - 使用uvicorn直接启动，绑定到Railway提供的端口
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"